title: Abbas Rizvi
description: Personal website of Abbas Rizvi — Computer Science student at the University of Alberta.
url: https://abbasalirizvi.com

markdown: kramdown
permalink: /:categories/:title/

include:
  - _pages

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/

plugins:
  - jekyll-sitemap

defaults:
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: page

author:
  name: Abbas Rizvi
  github: https://github.com/wowow2
  linkedin: https://www.linkedin.com/in/abbas-rizvi-6658a125b/
  resume: /assets/Abbas___Resume.pdf
